/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.Usuario;
import DAO.connectDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class TelaCadastrarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    public TelaCadastrarUsuario() {
        initComponents();
    }
    
    String operacaoAtivaGlobal = "Nenhum";

    public TelaCadastrarUsuario(String operacaoAtiva){
        initComponents();
        operacaoAtivaGlobal = operacaoAtiva;
        
        String operacao = "Incluir";
        if (operacaoAtiva.equals(operacao)) {
            this.setAllVisible(true);
        }
        
        operacao = "Alterar";
        String operacaoExcluir = "Excluir";
        if (operacaoAtiva.equals(operacao) || operacaoAtiva.equals(operacaoExcluir)) {
            this.setAllVisible(false);
            labelId.setVisible(true); 
            idCliente.setVisible(true);
            
            buttonCadastrar.setVisible(true);
            buttonCadastrar.setText("Pesquisar");
            buttonVoltar.setVisible(true);
        }
        
        
    }
    
    Usuario usuarioTela = new Usuario();
    boolean senhasIguais = false;

    
    
    private void setAllVisible(Boolean visible) {
        agenciaCliente.setVisible(visible);
        buttonCadastrar.setVisible(visible);
        buttonVoltar.setVisible(visible);
        confirmaSenha.setVisible(visible);
        contaCliente.setVisible(visible);
        idCliente.setVisible(visible);
        labelAgencia.setVisible(visible);
        labelConfirma.setVisible(visible);
        labelConta.setVisible(visible);
        labelId.setVisible(visible);
        labelSenha.setVisible(visible);
        senhaUsuario.setVisible(visible);
    }
    
    private void setAllEnabled(Boolean enabled) {
        agenciaCliente.setEnabled(enabled);
        buttonCadastrar.setEnabled(enabled);
        buttonVoltar.setEnabled(enabled);
        confirmaSenha.setEnabled(enabled);
        contaCliente.setEnabled(enabled);
        idCliente.setEnabled(enabled);
        labelAgencia.setEnabled(enabled);
        labelConfirma.setEnabled(enabled);
        labelConta.setEnabled(enabled);
        labelId.setEnabled(enabled);
        labelSenha.setEnabled(enabled);
        senhaUsuario.setEnabled(enabled);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelId = new javax.swing.JLabel();
        labelConta = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        idCliente = new javax.swing.JTextField();
        contaCliente = new javax.swing.JTextField();
        labelConfirma = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        buttonCadastrar = new javax.swing.JToggleButton();
        senhaUsuario = new javax.swing.JPasswordField();
        confirmaSenha = new javax.swing.JPasswordField();
        buttonVoltar = new javax.swing.JButton();
        agenciaCliente = new javax.swing.JTextField();
        labelAgencia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelId.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        labelId.setText("ID do Cliente:");

        labelConta.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        labelConta.setText("Num. Conta:");

        labelSenha.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        labelSenha.setText("Senha:");

        labelConfirma.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        labelConfirma.setText("Confirma:");

        errorLabel.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 0, 51));

        buttonCadastrar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        senhaUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificaSenha(evt);
            }
        });

        confirmaSenha.setToolTipText("");
        confirmaSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                verificaSenha(evt);
            }
        });

        buttonVoltar.setText("← Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarTelaMenu(evt);
            }
        });

        agenciaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agenciaClienteActionPerformed(evt);
            }
        });

        labelAgencia.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        labelAgencia.setText("Num. Agencia:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idCliente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(senhaUsuario))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelConfirma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(errorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(confirmaSenha)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonVoltar)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelAgencia)
                        .addGap(1, 1, 1)
                        .addComponent(agenciaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelConta)
                        .addGap(1, 1, 1)
                        .addComponent(contaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelAgencia)
                        .addComponent(agenciaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelConta)
                        .addComponent(contaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelConfirma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(buttonCadastrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        if (operacaoAtivaGlobal.equals("Incluir")){
            if (senhasIguais == false) {
                JOptionPane.showMessageDialog(this, "As senhas precisam ser iguais");
            }
            try {
                this.usuarioTela.setNumConta(this.contaCliente.getText());
                this.usuarioTela.setNumAgencia(this.agenciaCliente.getText());
                this.usuarioTela.setSenha(new String(this.senhaUsuario.getPassword()));
                this.usuarioTela.setIdUsuario(this.idCliente.getText());

                connectDAO connDAO = new connectDAO();
                connDAO.connectDB();
                connDAO.insereRegistroJFBD(this.usuarioTela);

            } catch (IllegalArgumentException err) {        
                JOptionPane.showMessageDialog(this, err.getMessage());
                return;
            }

            JOptionPane.showMessageDialog(this, "Usuário Cadastrado!");

            TelaMenu telaMenu = new TelaMenu();
            telaMenu.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
        
        if (operacaoAtivaGlobal.equals("Exclusão")) {
            connectDAO connDAO = new connectDAO();
            connDAO.connectDB();
            connDAO.excluiRegistroJFBD(this.usuarioTela);
            
            JOptionPane.showMessageDialog(this, "Usuario Excluído!");

            TelaMenu telaMenu = new TelaMenu();
            telaMenu.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
        
        if(operacaoAtivaGlobal.equals("Alteração")){
            try {
                this.usuarioTela.setNumConta(this.contaCliente.getText());
                this.usuarioTela.setNumAgencia(this.agenciaCliente.getText());
                this.usuarioTela.setSenha(new String(this.senhaUsuario.getPassword()));

                connectDAO connDAO = new connectDAO();
                connDAO.connectDB();
                connDAO.alteraRegistroJFBD(this.usuarioTela);

            } catch (IllegalArgumentException err) {        
                JOptionPane.showMessageDialog(this, err.getMessage());
                return;
            }
            JOptionPane.showMessageDialog(this, "Usuário Alterado!");

            TelaMenu telaMenu = new TelaMenu();
            telaMenu.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
        
        if (operacaoAtivaGlobal.equals("Alterar") || operacaoAtivaGlobal.equals("Excluir")){
            connectDAO connDAO = new connectDAO();
            
            this.usuarioTela.setIdUsuario(this.idCliente.getText());
            
            List<String> dadosSQL = connDAO.consultaRegistroJFBD(this.usuarioTela);
            
            this.usuarioTela.importaSQLValues(dadosSQL);
            
            
            this.contaCliente.setText(this.usuarioTela.getNumConta());
            this.agenciaCliente.setText(this.usuarioTela.getNumAgencia());
            this.senhaUsuario.setText(this.usuarioTela.getSenha());
            this.confirmaSenha.setText(this.usuarioTela.getSenha());
            this.idCliente.setText(String.valueOf(this.usuarioTela.getIdUsuario()) );
            
            
            this.setAllVisible(true);
            
            if (operacaoAtivaGlobal.equals("Excluir")) {
                buttonCadastrar.setText("Excluir");
                operacaoAtivaGlobal = "Exclusão";
                this.setAllEnabled(false);
                this.buttonVoltar.setEnabled(true);
                this.buttonCadastrar.setEnabled(true);
            } else {
                buttonCadastrar.setText("Alterar");
                operacaoAtivaGlobal = "Alteração";
            }
        }
    }//GEN-LAST:event_cadastrarActionPerformed

    private void verificaSenha(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificaSenha
        String strSenha = new String(this.senhaUsuario.getPassword());
        String strConfirma = new String(this.confirmaSenha.getPassword());
        if (strSenha.equals(strConfirma) || strConfirma.equals("")) {
            this.errorLabel.setText("");
            this.senhasIguais = true;
        } else {
            this.errorLabel.setText("As senhas não conferem.");
            this.senhasIguais = false;
        }
    }//GEN-LAST:event_verificaSenha

    private void voltarTelaMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarTelaMenu
        TelaMenu telaMenu = new TelaMenu();
        telaMenu.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_voltarTelaMenu

    private void agenciaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agenciaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agenciaClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agenciaCliente;
    private javax.swing.JToggleButton buttonCadastrar;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JPasswordField confirmaSenha;
    private javax.swing.JTextField contaCliente;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextField idCliente;
    private javax.swing.JLabel labelAgencia;
    private javax.swing.JLabel labelConfirma;
    private javax.swing.JLabel labelConta;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JPasswordField senhaUsuario;
    // End of variables declaration//GEN-END:variables
}
