/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.ExtratoMovimentacao;
import DAO.connectDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class TelaCadastrarExtratoMovimentacao extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastrarExtratoBancario
     */
    public TelaCadastrarExtratoMovimentacao() {
        initComponents();
    }
    
    String operacaoAtivaGlobal = "Nenhum";
    
    public TelaCadastrarExtratoMovimentacao(String operacaoAtiva) {
        initComponents();
        this.operacaoAtivaGlobal = operacaoAtiva;
        if (this.operacaoAtivaGlobal.equals("Incluir")){
            setAllVisible(true);
            setAllEnabled(true);
        }
        
        if (this.operacaoAtivaGlobal.equals("Alterar") || this.operacaoAtivaGlobal.equals("Excluir")){
            this.setAllVisible(false);
            labelDocumento.setVisible(true); 
            documento.setVisible(true);
            
            buttonCadastrar.setVisible(true);
            buttonCadastrar.setText("Pesquisar");
            buttonVoltar.setVisible(true);
        }
    }
    
    ExtratoMovimentacao extratoMovimentacaoTela = new ExtratoMovimentacao();

    private void setAllVisible(boolean isVisible){
        labelIdHis.setVisible(isVisible);
        idHis.setVisible(isVisible);
        labelAgencia.setVisible(isVisible);
        numAgencia.setVisible(isVisible);
        labelConta.setVisible(isVisible);
        numConta.setVisible(isVisible);
        labelData.setVisible(isVisible);
        dataMovimento.setVisible(isVisible);
        labelDocumento.setVisible(isVisible);
        documento.setVisible(isVisible);
        labelTransacao.setVisible(isVisible);
        meioTransacao.setVisible(isVisible);
        labelValor.setVisible(isVisible);
        valor.setVisible(isVisible);
        labelSaldo.setVisible(isVisible);
        saldo.setVisible(isVisible);
        labelHistCompl.setVisible(isVisible);
        histCompleto.setVisible(isVisible);
        jScrollPane1.setVisible(isVisible);
        
        buttonCadastrar.setVisible(isVisible);
        buttonLimpar.setVisible(isVisible);
    }
    
    
    private void setAllEnabled(boolean isEnabled){
        labelIdHis.setEnabled(isEnabled);
        idHis.setEnabled(isEnabled);
        labelAgencia.setEnabled(isEnabled);
        numAgencia.setEnabled(isEnabled);
        labelConta.setEnabled(isEnabled);
        numConta.setEnabled(isEnabled);
        labelData.setEnabled(isEnabled);
        dataMovimento.setEnabled(isEnabled);
        labelDocumento.setEnabled(isEnabled);
        documento.setEnabled(isEnabled);
        labelTransacao.setEnabled(isEnabled);
        meioTransacao.setEnabled(isEnabled);
        labelValor.setEnabled(isEnabled);
        valor.setEnabled(isEnabled);
        labelSaldo.setEnabled(isEnabled);
        saldo.setEnabled(isEnabled);
        labelHistCompl.setEnabled(isEnabled);
        histCompleto.setEnabled(isEnabled);
        jScrollPane1.setEnabled(isEnabled);
        
        buttonCadastrar.setEnabled(isEnabled);
        buttonLimpar.setEnabled(isEnabled);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelConta = new javax.swing.JLabel();
        labelAgencia = new javax.swing.JLabel();
        labelIdHis = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        labelSaldo = new javax.swing.JLabel();
        labelTransacao = new javax.swing.JLabel();
        labelHistCompl = new javax.swing.JLabel();
        labelDocumento = new javax.swing.JLabel();
        labelValor = new javax.swing.JLabel();
        idHis = new javax.swing.JTextField();
        numAgencia = new javax.swing.JTextField();
        numConta = new javax.swing.JTextField();
        dataMovimento = new javax.swing.JTextField();
        meioTransacao = new javax.swing.JComboBox<>();
        documento = new javax.swing.JTextField();
        valor = new javax.swing.JTextField();
        saldo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        histCompleto = new javax.swing.JTextArea();
        buttonCadastrar = new javax.swing.JButton();
        buttonLimpar = new javax.swing.JButton();
        buttonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelConta.setText("Conta:");

        labelAgencia.setText("Agência:");

        labelIdHis.setText("ID Histórico:");

        labelData.setText("Data Movimento:");

        labelSaldo.setText("Saldo:");

        labelTransacao.setText("Meio transação:");

        labelHistCompl.setText("Histórico Completo:");

        labelDocumento.setText("Documento:");

        labelValor.setText("Valor:");

        meioTransacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Débito", "Crédito" }));

        valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorActionPerformed(evt);
            }
        });

        histCompleto.setColumns(20);
        histCompleto.setRows(5);
        jScrollPane1.setViewportView(histCompleto);

        buttonCadastrar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarcadastrarActionPerformed(evt);
            }
        });

        buttonLimpar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        buttonLimpar.setText("Limpar");
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparlimparActionPerformed(evt);
            }
        });

        buttonVoltar.setText("← Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarTelaMenu(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonVoltar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelIdHis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idHis, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelAgencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelConta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numConta))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTransacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(meioTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSaldo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saldo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelHistCompl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonCadastrar)
                                .addGap(380, 380, 380)
                                .addComponent(buttonLimpar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDocumento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(documento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDocumento)
                    .addComponent(documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dataMovimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelData)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdHis)
                    .addComponent(labelAgencia)
                    .addComponent(labelConta)
                    .addComponent(idHis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTransacao)
                    .addComponent(meioTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValor)
                    .addComponent(labelSaldo)
                    .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(labelHistCompl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLimpar)
                    .addComponent(buttonCadastrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorActionPerformed

    private void buttonCadastrarcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarcadastrarActionPerformed
        if (operacaoAtivaGlobal.equals("Incluir")){
            try {
                this.extratoMovimentacaoTela.setId_his(Integer.parseInt(this.idHis.getText()));
                this.extratoMovimentacaoTela.setNumAgencia(this.numAgencia.getText());
                this.extratoMovimentacaoTela.setNumConta(this.numConta.getText());
                SimpleDateFormat dateFormater = new SimpleDateFormat("dd/MM/yyyy");
                Date dataMovimentoFormatada = dateFormater.parse(this.dataMovimento.getText());
                this.extratoMovimentacaoTela.setDataMovimento(dataMovimentoFormatada);
                this.extratoMovimentacaoTela.setDocumento(this.documento.getText());
                this.extratoMovimentacaoTela.setCreditoDebito(this.meioTransacao.getSelectedItem().toString().substring(0, 1));
                this.extratoMovimentacaoTela.setValor(Integer.parseInt(this.valor.getText()));
                this.extratoMovimentacaoTela.setSaldo(Integer.parseInt(this.saldo.getText()));
                this.extratoMovimentacaoTela.setComplHist(this.histCompleto.getText());

                connectDAO connDAO = new connectDAO();
                connDAO.connectDB();
                connDAO.insereRegistroJFBD(this.extratoMovimentacaoTela);

            } catch (IllegalArgumentException | ParseException err) {
                JOptionPane.showMessageDialog(this, err.getMessage());
                return;
            }
            JOptionPane.showMessageDialog(this, "Extrato de Movimentação Cadastrado!");

            TelaMenu telaMenu = new TelaMenu();
            telaMenu.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
        
        
        if (operacaoAtivaGlobal.equals("Exclusão")) {
            connectDAO connDAO = new connectDAO();
            connDAO.connectDB();
            connDAO.excluiRegistroJFBD(this.extratoMovimentacaoTela);
            
            JOptionPane.showMessageDialog(this, "Extrato Excluído!");

            TelaMenu telaMenu = new TelaMenu();
            telaMenu.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
        
        if(operacaoAtivaGlobal.equals("Alteração")){
            try {
                this.extratoMovimentacaoTela.setId_his(Integer.parseInt(this.idHis.getText()));
                this.extratoMovimentacaoTela.setNumAgencia(this.numAgencia.getText());
                this.extratoMovimentacaoTela.setNumConta(this.numConta.getText());
                SimpleDateFormat dateFormater = new SimpleDateFormat("dd/MM/yyyy");
                Date dataMovimentoFormatada = dateFormater.parse(this.dataMovimento.getText());
                this.extratoMovimentacaoTela.setDataMovimento(dataMovimentoFormatada);
                this.extratoMovimentacaoTela.setDocumento(this.documento.getText());
                this.extratoMovimentacaoTela.setCreditoDebito(this.meioTransacao.getSelectedItem().toString().substring(0, 1));
                this.extratoMovimentacaoTela.setValor(Double.parseDouble(this.valor.getText()));
                this.extratoMovimentacaoTela.setSaldo(Double.parseDouble(this.saldo.getText()));
                this.extratoMovimentacaoTela.setComplHist(this.histCompleto.getText());

                connectDAO connDAO = new connectDAO();
                connDAO.connectDB();
                connDAO.alteraRegistroJFBD(this.extratoMovimentacaoTela);

            } catch (IllegalArgumentException | ParseException err) {        
                JOptionPane.showMessageDialog(this, err.getMessage());
                return;
            }
            JOptionPane.showMessageDialog(this, "Usuário Alterado!");

            TelaMenu telaMenu = new TelaMenu();
            telaMenu.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
        
        if (operacaoAtivaGlobal.equals("Alterar") || operacaoAtivaGlobal.equals("Excluir")){
            connectDAO connDAO = new connectDAO();
            
            this.extratoMovimentacaoTela.setDocumento(this.documento.getText());
            
            List<String> dadosSQL = connDAO.consultaRegistroJFBD(this.extratoMovimentacaoTela);
            
            this.extratoMovimentacaoTela.importaSQLValues(dadosSQL);
            
            
            this.idHis.setText( String.valueOf(this.extratoMovimentacaoTela.getId_his()));
            this.numAgencia.setText(this.extratoMovimentacaoTela.getNumAgencia());
            this.numConta.setText(this.extratoMovimentacaoTela.getNumConta());
            SimpleDateFormat dateFormater = new SimpleDateFormat("dd/MM/yyyy");
            String dataMovimentoFormatada = dateFormater.format(this.extratoMovimentacaoTela.getDataMovimento());
            this.dataMovimento.setText(dataMovimentoFormatada);
            this.documento.setText(this.extratoMovimentacaoTela.getDocumento());
            String creditoDebito = "Débito";
            if (this.extratoMovimentacaoTela.getCreditoDebito().equals("C")) {
                creditoDebito = "Crédito";
            }
            this.meioTransacao.setSelectedItem(creditoDebito);
            this.valor.setText(String.valueOf(this.extratoMovimentacaoTela.getValor()));
            this.saldo.setText(String.valueOf(this.extratoMovimentacaoTela.getSaldo()));
            this.histCompleto.setText(this.extratoMovimentacaoTela.getComplHist());
            
            this.setAllVisible(true);
            
            if (operacaoAtivaGlobal.equals("Excluir")) {
                buttonCadastrar.setText("Excluir");
                operacaoAtivaGlobal = "Exclusão";
                this.setAllEnabled(false);
                this.buttonVoltar.setEnabled(true);
                this.buttonCadastrar.setEnabled(true);
            } else {
                buttonCadastrar.setText("Alterar");
                operacaoAtivaGlobal = "Alteração";
            }
        }
    }//GEN-LAST:event_buttonCadastrarcadastrarActionPerformed

    private void buttonLimparlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparlimparActionPerformed
        this.idHis.setText("");
        this.numAgencia.setText("");
        this.numConta.setText("");
        this.dataMovimento.setText("");
        this.documento.setText("");
        this.meioTransacao.setSelectedIndex(0);
        this.valor.setText("");
        this.saldo.setText("");
        this.histCompleto.setText("");
    }//GEN-LAST:event_buttonLimparlimparActionPerformed

    private void voltarTelaMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarTelaMenu
        TelaMenu telaMenu = new TelaMenu();
        telaMenu.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_voltarTelaMenu

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarExtratoMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarExtratoMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarExtratoMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarExtratoMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrarExtratoMovimentacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JTextField dataMovimento;
    private javax.swing.JTextField documento;
    private javax.swing.JTextArea histCompleto;
    private javax.swing.JTextField idHis;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAgencia;
    private javax.swing.JLabel labelConta;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelDocumento;
    private javax.swing.JLabel labelHistCompl;
    private javax.swing.JLabel labelIdHis;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JLabel labelTransacao;
    private javax.swing.JLabel labelValor;
    private javax.swing.JComboBox<String> meioTransacao;
    private javax.swing.JTextField numAgencia;
    private javax.swing.JTextField numConta;
    private javax.swing.JTextField saldo;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
